stages:
  - build
  - deploy

variables:
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "knowledgecity-frontend"

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: amazon/aws-cli
  script:
    - aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
    - aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
