stages:
  - build
  - deploy

variables:
  AWS_REGION: "us-east-1"
  EKS_CLUSTER_NAME: "knowledgecity-eks"

build:
  stage: build
  image: docker:20
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
  script:
    - kubectl apply -f k8s/deployment.yaml
