apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server
  labels:
    app: media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-server
  template:
    metadata:
      labels:
        app: media-server
    spec:
      containers:
      - name: media-server
        image: <YOUR_DOCKER_IMAGE>
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: media-server
spec:
  selector:
    app: media-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
