apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-api
  labels:
    app: monolithic-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monolithic-api
  template:
    metadata:
      labels:
        app: monolithic-api
    spec:
      containers:
        - name: monolithic-api
          image: <YOUR_DOCKER_IMAGE>
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: <DATABASE_HOST>
            - name: DB_USER
              value: <DATABASE_USER>
            - name: DB_PASSWORD
              value: <DATABASE_PASSWORD>
---
apiVersion: v1
kind: Service
metadata:
  name: monolithic-api
spec:
  selector:
    app: monolithic-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
